image:
  file: .gitpod.Dockerfile
tasks:
  - name: Start
    init: npm install && gp sync-done install
    command: npm run start
  - name: Storybook
    init: gp sync-await install
    command: npm run visual
ports:
  - port: 36687
    onOpen: open-preview
